### ISSUE TITLE
ERROR: Failed to remove reparse point

### ISSUE THREAD

**Issue by RickCopithorne** [marceln/SuperDelete#6]
Trying to use these to delete some unwanted NAS files copied onto a clean Windows 2016 partition. Files over the 256 character limit have been a pain. When I try to run this command against large directories or files i get the error

**Comment by marceln** [comment]
Hey,

Can you please run it with --printStackTrace and post the entire error here?

Marcel

**Comment by RickCopithorne** [comment]
Error: System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid. Failed to remove reparse point

   at SuperDelete.Internal.FileDeleter.ThrowLastErrorException(Int32 error, String message, Object[] args)
   at SuperDelete.Internal.FileDeleter.DeleteFolder(String folderPath, Boolean bypassAclCheck, FileAttributes parentAttributes)
   at SuperDelete.Internal.FileDeleter.DeleteFolder(String folderPath, Boolean bypassAclCheck, FileAttributes parentAttributes)
   at SuperDelete.Internal.FileDeleter.DeleteFolder(String folderPath, Boolean bypassAclCheck, FileAttributes parentAttributes)
   at SuperDelete.Internal.FileDeleter.DeleteFolder(String folderPath, Boolean bypassAclCheck, FileAttributes parentAttributes)
   at SuperDelete.Internal.FileDeleter.DeleteFolder(String folderPath, Boolean bypassAclCheck, FileAttributes parentAttributes)
   at SuperDelete.Internal.FileDeleter.DeleteFolder(String folderPath, Boolean bypassAclCheck, FileAttributes parentAttributes)
   at SuperDelete.Internal.FileDeleter.DeleteFolder(String folderPath, Boolean bypassAclCheck, FileAttributes parentAttributes)
   at SuperDelete.Program.Main(String[] args)
Done. Deleted 0 files and 0 folders in 00:00:00.

**Comment by RickCopithorne** [comment]
I had to remove the output showing path name as it contained sensitive info,here is a visual blacked out. 
![SuperDelError](https://user-images.githubusercontent.com/57911020/88093897-ae500480-cb60-11ea-83e4-43145d4d9d14.JPG)
